### ISSUE TITLE
No effect at all, no output to the file

### ISSUE THREAD

**Issue by Tudsday** [wudicgi/SpleeterMsvcExe#2]
No effect at all, no output to the file
win11 22621 x64

**Comment by wudicgi** [comment]
More information is needed, such as the executed command line and the entire output logs.

You may check the following points first:
- If the "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" has installed
- If the Spleeter model files (in separated release) have been downloaded and extracted to "models" folder
