### ISSUE TITLE
Can you create a GUI for batch files render ?

### ISSUE THREAD

**Issue by tranvantruong801** [wudicgi/SpleeterMsvcExe#5]

**Comment by wudicgi** [comment]
There is a GUI program named SpleeterGui in developing, since July 2022.
But it still has some details to be completed, and the code has not been released.

Currently, it looks like this:
![image](https://user-images.githubusercontent.com/2692176/213716222-c40c17a1-6c32-447a-b25b-3e914f79b503.png)

**Comment by wudicgi** [comment]
The Spleeter GUI program has been released.
See https://github.com/wudicgi/SpleeterGui/releases
